/* Blog index — generated by build_posts.py from the post pages. */
export const posts = [
  {
    "slug": "25years",
    "title": "25 Years on This Planet: Lessons Taught by Time",
    "plain": "25 Years on This Planet: Lessons Taught by Time",
    "kind": "Photo Journal",
    "date": "Jul 18, 2026",
    "read": 4,
    "excerpt": "I will be turning twenty-five this year, and twenty-five is not old. But it is old enough to have been wrong about important things, to have lost people you thought would stay, and to have…",
    "cover": "assets/C3BFE7AA-A9C0-4104-81F6-EE241B48056D_1_105_c.webp"
  },
  {
    "slug": "chaos",
    "title": "A sound of Thunder:<br>The Science of Chaos",
    "plain": "A sound of Thunder: The Science of Chaos",
    "kind": "Science",
    "date": "Jun 28, 2055",
    "read": 6,
    "excerpt": "Ask someone what changed the way scientists think about prediction, and very few will say a butterfly. But that's more or less what happened. Somewhere between a work of science fiction…",
    "cover": "assets/forest-on-head.webp"
  },
  {
    "slug": "chernobyl",
    "title": "So tell me, how does a<br>RBMK reactor explode?",
    "plain": "So tell me, how does a RBMK reactor explode?",
    "kind": "History",
    "date": "Aug 20, 2021",
    "read": 7,
    "excerpt": "The Chernobyl disaster is, to date, the most severe nuclear disaster in the recorded history of mankind. Many people still believe that reactor number 4 at the Vladimir I. Lenin Nuclear…",
    "cover": "assets/reactorChernobly.webp"
  },
  {
    "slug": "creativity",
    "title": "Why I Believe Creativity Is a Process Rather Than a Static Skill Set",
    "plain": "Why I Believe Creativity Is a Process Rather Than a Static Skill Set",
    "kind": "Personal Essay",
    "date": "Jul 18, 2026",
    "read": 5,
    "excerpt": "If someone asked me when I became a creative person, I honestly wouldn't know what to say. There wasn't a day I woke up and decided I wanted to become a designer, an animator, or a…",
    "cover": "assets/Infinity copy.webp"
  },
  {
    "slug": "mountains",
    "title": "The Call of the Mountains",
    "plain": "The Call of the Mountains",
    "kind": "Photo Essay",
    "date": "Jul 18, 2026",
    "read": 5,
    "excerpt": "For as long as I can remember, the debate between mountains and beaches has never really had a winner. Everyone seems to have a side. Personally, I've never been able to choose — both have…",
    "cover": "assets/4D4A9268-D89D-4B09-B78F-DF51096F0645_1_105_c.webp"
  },
  {
    "slug": "patna",
    "title": "What I Learned from the Streets of Patna",
    "plain": "What I Learned from the Streets of Patna",
    "kind": "Visual Story Essay",
    "date": "Sept 12, 2023",
    "read": 7,
    "excerpt": "Nearly nine years ago, I picked up a camera with nothing more than curiosity. What began during my senior secondary school days as a hobby slowly turned into a passion that accompanied me…",
    "cover": "assets/patna-elder-portrait.webp"
  },
  {
    "slug": "research",
    "title": "Learning Through<br>Research Methodology",
    "plain": "Learning Through Research Methodology",
    "kind": "Research & Academia",
    "date": "Jul 18, 2026",
    "read": 4,
    "excerpt": "After nearly sixteen years of formal education—twelve years in school followed by undergraduate or postgraduate studies—most of us have experienced almost every major teaching methodology.…",
    "cover": "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  },
  {
    "slug": "steel",
    "title": "The Art of Transforming<br>Iron to Steel",
    "plain": "The Art of Transforming Iron to Steel",
    "kind": "Engineering",
    "date": "Aug 24, 2021",
    "read": 5,
    "excerpt": "When I ask people what the world's most recycled material is, the answers are almost always the same—plastic, paper, maybe even rubber. Very few guess the correct answer: steel. It is one…",
    "cover": "assets/kepinator-metallurgy-2932947.webp"
  }
];
export const hrefOf = (slug) => `blog-${slug}.html`;
